### ISSUE TITLE
please need some help 

### ISSUE THREAD

**Issue by klunsen** [pieteroskam/autopilot#2]
c:/users/klunsen/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:\Users\klunsen\AppData\Local\Temp\arduino\cores\b014e8a2e2409a6c2db58ea7a85eb4b2\core.a(esp32-hal-ledc.c.o): in function `analogWriteResolution':
C:\Users\klunsen\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.8\cores\esp32/esp32-hal-ledc.c:252: multiple definition of `analogWriteResolution'; C:\Users\klunsen\AppData\Local\Temp\arduino\sketches\F965C8C3149A289F8C4CE33DBC5ACE57\libraries\ESP32_AnalogWrite\analogWrite.cpp.o:c:\Users\klunsen\Documents\Arduino\libraries\ESP32_AnalogWrite/analogWrite.cpp:74: first defined here
collect2.exe: error: ld returned 1 exit status

exit status 1

Compilation error: exit status 1

**Comment by pieteroskam** [comment]
Klunsen, closing this. How are you doing?
