### ISSUE TITLE
compilation issue

### ISSUE THREAD

**Issue by svdrummer** [pieteroskam/autopilot#4]
Has anyone compiled the current version?

I am getting
Documents\Arduino\libraries\ESP32_BLE_Arduino\src/FreeRTOS.h:61:28: error: 'ringbuf_type_t' has not been declared
  Ringbuffer(size_t length, ringbuf_type_t type = RINGBUF_TYPE_NOSPLIT);
                            ^~~~~~~~~~~~~~
 and others related to blue tooth.

**Comment by svdrummer** [comment]
C:\Users\cruis\Downloads\autopilot-main\autopilot-main\autopilot_basic\Bluetooth.cpp:1:2: error: 'Bluetooth' does not name a type
  Bluetooth.cpp
  ^~~~~~~~~
In file included from C:\Users\cruis\OneDrive\Documents\Arduino\libraries\ESP32_BLE_Arduino\src/BLEAdvertising.h:15,
                 from C:\Users\cruis\OneDrive\Documents\Arduino\libraries\ESP32_BLE_Arduino\src/BLEServer.h:19,
                 from C:\Users\cruis\Downloads\autopilot-main\autopilot-main\autopilot_basic\Bluetooth.h:9,
                 from C:\Users\cruis\Downloads\autopilot-main\autopilot-main\autopilot_basic\Bluetooth.cpp:2:
C:\Users\cruis\OneDrive\Documents\Arduino\libraries\ESP32_BLE_Arduino\src/FreeRTOS.h:61:28: error: 'ringbuf_type_t' has not been declared
  Ringbuffer(size_t length, ringbuf_type_t type = RINGBUF_TYPE_NOSPLIT);
                            ^~~~~~~~~~~~~~
In file included from C:\Users\cruis\OneDrive\Documents\Arduino\libraries\ESP32_BLE_Arduino\src/BLEAdvertising.h:15,
                 from C:\Users\cruis\OneDrive\Documents\Arduino\libraries\ESP32_BLE_Arduino\src/BLEServer.h:19,
                 from C:\Users\cruis\Downloads\autopilot-main\autopilot-main\autopilot_basic\Bluetooth.h:9,
                 from C:\Users\cruis\Downloads\autopilot-main\autopilot-main\autopilot_basic\autopilot_basic.ino:25:
C:\Users\cruis\OneDrive\Documents\Arduino\libraries\ESP32_BLE_Arduino\src/FreeRTOS.h:61:28: error: 'ringbuf_type_t' has not been declared
  Ringbuffer(size_t length, ringbuf_type_t type = RINGBUF_TYPE_NOSPLIT);
                            ^~~~~~~~~~~~~~
In file included from C:\Users\cruis\OneDrive\Documents\Arduino\libraries\ESP32_BLE_Arduino\src/BLECharacteristic.h:17,
                 from C:\Users\cruis\OneDrive\Documents\Arduino\libraries\ESP32_BLE_Arduino\src/BLEServer.h:20,
                 from C:\Users\cruis\Downloads\autopilot-main\autopilot-main\autopilot_basic\Bluetooth.h:9,
                 from C:\Users\cruis\Downloads\autopilot-main\autopilot-main\autopilot_basic\Bluetooth.cpp:2:
C:\Users\cruis\OneDrive\Documents\Arduino\libraries\ESP32_BLE_Arduino\src/BLEDescriptor.h:25:7: error: redefinition of 'class BLEDescriptor'
 class BLEDescriptor {
       ^~~~~~~~~~~~~
In file included from C:\Users\cruis\OneDrive\Documents\Arduino\libraries\ArduinoBLE\src/BLECharacteristic.h:25,
                 from C:\Users\cruis\OneDrive\Documents\Arduino\libraries\ArduinoBLE\src/BLEService.h:23,
                 from C:\Users\cruis\OneDrive\Documents\Arduino\libraries\ArduinoBLE\src/BLEDevice.h:25,
                 from C:\Users\cruis\Downloads\autopilot-main\autopilot-main\autopilot_basic\Bluetooth.h:8,
                 from C:\Users\cruis\Downloads\autopilot-main\autopilot-main\autopilot_basic\Bluetooth.cpp:2:
C:\Users\cruis\OneDrive\Documents\Arduino\libraries\ArduinoBLE\src/BLEDescriptor.h:28:7: note: previous definition of 'class BLEDescriptor'
 class BLEDescriptor {
       ^~~~~~~~~~~~~
In file included from C:\Users\cruis\OneDrive\Documents\Arduino\libraries\ESP32_BLE_Arduino\src/BLEServer.h:20,
                 from C:\Users\cruis\Downloads\autopilot-main\autopilot-main\autopilot_basic\Bluetooth.h:9,
                 from C:\Users\cruis\Downloads\autopilot-main\autopilot-main\autopilot_basic\Bluetooth.cpp:2:
C:\Users\cruis\OneDrive\Documents\Arduino\libraries\ESP32_BLE_Arduino\src/BLECharacteristic.h:53:7: error: redefinition of 'class BLECharacteristic'
 class BLECharacteristic {
       ^~~~~~~~~~~~~~~~~
In file included from C:\Users\cruis\OneDrive\Documents\Arduino\libraries\ArduinoBLE\src/BLEService.h:23,
                 from C:\Users\cruis\OneDrive\Documents\Arduino\libraries\ArduinoBLE\src/BLEDevice.h:25,
                 from C:\Users\cruis\Downloads\autopilot-main\autopilot-main\autopilot_basic\Bluetooth.h:8,
                 from C:\Users\cruis\Downloads\autopilot-main\autopilot-main\autopilot_basic\Bluetooth.cpp:2:
C:\Users\cruis\OneDrive\Documents\Arduino\libraries\ArduinoBLE\src/BLECharacteristic.h:45:7: note: previous definition of 'class BLECharacteristic'
 class BLECharacteristic  {
       ^~~~~~~~~~~~~~~~~
In file included from C:\Users\cruis\OneDrive\Documents\Arduino\libraries\ESP32_BLE_Arduino\src/BLECharacteristic.h:17,
                 from C:\Users\cruis\OneDrive\Documents\Arduino\libraries\ESP32_BLE_Arduino\src/BLEServer.h:20,
                 from C:\Users\cruis\Downloads\autopilot-main\autopilot-main\autopilot_basic\Bluetooth.h:9,
                 from C:\Users\cruis\Downloads\autopilot-main\autopilot-main\autopilot_basic\autopilot_basic.ino:25:
C:\Users\cruis\OneDrive\Documents\Arduino\libraries\ESP32_BLE_Arduino\src/BLEDescriptor.h:25:7: error: redefinition of 'class BLEDescriptor'
 class BLEDescriptor {
       ^~~~~~~~~~~~~
In file included from C:\Users\cruis\OneDrive\Documents\Arduino\libraries\ArduinoBLE\src/BLECharacteristic.h:25,
                 from C:\Users\cruis\OneDrive\Documents\Arduino\libraries\ArduinoBLE\src/BLEService.h:23,
                 from C:\Users\cruis\OneDrive\Documents\Arduino\libraries\ArduinoBLE\src/BLEDevice.h:25,
                 from C:\Users\cruis\Downloads\autopilot-main\autopilot-main\autopilot_basic\Bluetooth.h:8,
                 from C:\Users\cruis\Downloads\autopilot-main\autopilot-main\autopilot_basic\autopilot_basic.ino:25:
C:\Users\cruis\OneDrive\Documents\Arduino\libraries\ArduinoBLE\src/BLEDescriptor.h:28:7: note: previous definition of 'class BLEDescriptor'
 class BLEDescriptor {
       ^~~~~~~~~~~~~
In file included from C:\Users\cruis\OneDrive\Documents\Arduino\libraries\ESP32_BLE_Arduino\src/BLEServer.h:21,
                 from C:\Users\cruis\Downloads\autopilot-main\autopilot-main\autopilot_basic\Bluetooth.h:9,
                 from C:\Users\cruis\Downloads\autopilot-main\autopilot-main\autopilot_basic\Bluetooth.cpp:2:
C:\Users\cruis\OneDrive\Documents\Arduino\libraries\ESP32_BLE_Arduino\src/BLEService.h:49:7: error: redefinition of 'class BLEService'
 class BLEService {
       ^~~~~~~~~~
In file included from C:\Users\cruis\OneDrive\Documents\Arduino\libraries\ArduinoBLE\src/BLEDevice.h:25,
                 from C:\Users\cruis\Downloads\autopilot-main\autopilot-main\autopilot_basic\Bluetooth.h:8,
                 from C:\Users\cruis\Downloads\autopilot-main\autopilot-main\autopilot_basic\Bluetooth.cpp:2:
C:\Users\cruis\OneDrive\Documents\Arduino\libraries\ArduinoBLE\src/BLEService.h:28:7: note: previous definition of 'class BLEService'
 class BLEService {
       ^~~~~~~~~~
In file included from C:\Users\cruis\OneDrive\Documents\Arduino\libraries\ESP32_BLE_Arduino\src/BLEServer.h:20,
                 from C:\Users\cruis\Downloads\autopilot-main\autopilot-main\autopilot_basic\Bluetooth.h:9,
                 from C:\Users\cruis\Downloads\autopilot-main\autopilot-main\autopilot_basic\autopilot_basic.ino:25:
C:\Users\cruis\OneDrive\Documents\Arduino\libraries\ESP32_BLE_Arduino\src/BLECharacteristic.h:53:7: error: redefinition of 'class BLECharacteristic'
 class BLECharacteristic {
       ^~~~~~~~~~~~~~~~~
In file included from C:\Users\cruis\OneDrive\Documents\Arduino\libraries\ArduinoBLE\src/BLEService.h:23,
                 from C:\Users\cruis\OneDrive\Documents\Arduino\libraries\ArduinoBLE\src/BLEDevice.h:25,
                 from C:\Users\cruis\Downloads\autopilot-main\autopilot-main\autopilot_basic\Bluetooth.h:8,
                 from C:\Users\cruis\Downloads\autopilot-main\autopilot-main\autopilot_basic\autopilot_basic.ino:25:
C:\Users\cruis\OneDrive\Documents\Arduino\libraries\ArduinoBLE\src/BLECharacteristic.h:45:7: note: previous definition of 'class BLECharacteristic'
 class BLECharacteristic  {
       ^~~~~~~~~~~~~~~~~
In file included from C:\Users\cruis\OneDrive\Documents\Arduino\libraries\ESP32_BLE_Arduino\src/BLEServer.h:21,
                 from C:\Users\cruis\Downloads\autopilot-main\autopilot-main\autopilot_basic\Bluetooth.h:9,
                 from C:\Users\cruis\Downloads\autopilot-main\autopilot-main\autopilot_basic\autopilot_basic.ino:25:
C:\Users\cruis\OneDrive\Documents\Arduino\libraries\ESP32_BLE_Arduino\src/BLEService.h:49:7: error: redefinition of 'class BLEService'
 class BLEService {
       ^~~~~~~~~~
In file included from C:\Users\cruis\OneDrive\Documents\Arduino\libraries\ArduinoBLE\src/BLEDevice.h:25,
                 from C:\Users\cruis\Downloads\autopilot-main\autopilot-main\autopilot_basic\Bluetooth.h:8,
                 from C:\Users\cruis\Downloads\autopilot-main\autopilot-main\autopilot_basic\autopilot_basic.ino:25:
C:\Users\cruis\OneDrive\Documents\Arduino\libraries\ArduinoBLE\src/BLEService.h:28:7: note: previous definition of 'class BLEService'
 class BLEService {
       ^~~~~~~~~~
C:\Users\cruis\Downloads\autopilot-main\autopilot-main\autopilot_basic\Bluetooth.cpp: In member function 'virtual void MyCallbacks::onWrite(BLECharacteristic*)':
C:\Users\cruis\Downloads\autopilot-main\autopilot-main\autopilot_basic\Bluetooth.cpp:69:44: error: 'class BLECharacteristic' has no member named 'getValue'; did you mean 'setValue'?
     std::string rxValue = pCharacteristic->getValue();
                                            ^~~~~~~~
                                            setValue
C:\Users\cruis\Downloads\autopilot-main\autopilot-main\autopilot_basic\Bluetooth.cpp: In member function 'virtual void otaCallback::onWrite(BLECharacteristic*)':
C:\Users\cruis\Downloads\autopilot-main\autopilot-main\autopilot_basic\Bluetooth.cpp:107:43: error: 'class BLECharacteristic' has no member named 'getValue'; did you mean 'setValue'?
     std::string rxData = pCharacteristic->getValue();
                                           ^~~~~~~~
                                           setValue
C:\Users\cruis\Downloads\autopilot-main\autopilot-main\autopilot_basic\Bluetooth.cpp:140:22: error: 'class BLECharacteristic' has no member named 'notify'
     pCharacteristic->notify();
                      ^~~~~~
C:\Users\cruis\Downloads\autopilot-main\autopilot-main\autopilot_basic\Bluetooth.cpp: In static member function 'static void Bluetooth::notify(BLECharacteristic*, String)':
C:\Users\cruis\Downloads\autopilot-main\autopilot-main\autopilot_basic\Bluetooth.cpp:149:19: error: 'class BLECharacteristic' has no member named 'notify'
   characteristic->notify();
                   ^~~~~~
C:\Users\cruis\Downloads\autopilot-main\autopilot-main\autopilot_basic\Bluetooth.cpp: In static member function 'static void Bluetooth::setup()':
C:\Users\cruis\Downloads\autopilot-main\autopilot-main\autopilot_basic\Bluetooth.cpp:158:14: error: 'init' is not a member of 'BLEDevice'
   BLEDevice::init("AutoPilot");
              ^~~~
C:\Users\cruis\Downloads\autopilot-main\autopilot-main\autopilot_basic\Bluetooth.cpp:159:24: error: 'createServer' is not a member of 'BLEDevice'
   pServer = BLEDevice::createServer();
                        ^~~~~~~~~~~~
C:\Users\cruis\Downloads\autopilot-main\autopilot-main\autopilot_basic\Bluetooth.cpp:167:52: error: 'class BLEService' has no member named 'createCharacteristic'; did you mean 'addCharacteristic'?
   BLECharacteristic *pRxCharacteristic = pService->createCharacteristic(UUID_RECEIVE, BLECharacteristic::PROPERTY_WRITE);
                                                    ^~~~~~~~~~~~~~~~~~~~
                                                    addCharacteristic
C:\Users\cruis\Downloads\autopilot-main\autopilot-main\autopilot_basic\Bluetooth.cpp:167:106: error: 'PROPERTY_WRITE' is not a member of 'BLECharacteristic'
   BLECharacteristic *pRxCharacteristic = pService->createCharacteristic(UUID_RECEIVE, BLECharacteristic::PROPERTY_WRITE);
                                                                                                          ^~~~~~~~~~~~~~
C:\Users\cruis\Downloads\autopilot-main\autopilot-main\autopilot_basic\Bluetooth.cpp:168:22: error: 'class BLECharacteristic' has no member named 'setCallbacks'
   pRxCharacteristic->setCallbacks(new MyCallbacks());
                      ^~~~~~~~~~~~
C:\Users\cruis\Downloads\autopilot-main\autopilot-main\autopilot_basic\Bluetooth.cpp:170:13: error: 'class BLEService' has no member named 'start'
   pService->start();
             ^~~~~
C:\Users\cruis\Downloads\autopilot-main\autopilot-main\autopilot_basic\Bluetooth.cpp:176:41: error: 'class BLEService' has no member named 'createCharacteristic'; did you mean 'addCharacteristic'?
   Version_Characteristic = pOTAService->createCharacteristic(UUID_VERSION, BLECharacteristic::PROPERTY_READ);
                                         ^~~~~~~~~~~~~~~~~~~~
                                         addCharacteristic
C:\Users\cruis\Downloads\autopilot-main\autopilot-main\autopilot_basic\Bluetooth.cpp:176:95: error: 'PROPERTY_READ' is not a member of 'BLECharacteristic'
   Version_Characteristic = pOTAService->createCharacteristic(UUID_VERSION, BLECharacteristic::PROPERTY_READ);
                                                                                               ^~~~~~~~~~~~~
C:\Users\cruis\Downloads\autopilot-main\autopilot-main\autopilot_basic\Bluetooth.cpp:177:54: error: no matching function for call to 'BLECharacteristic::addDescriptor(BLE2902*)'
   Version_Characteristic->addDescriptor(new BLE2902());
                                                      ^
In file included from C:\Users\cruis\OneDrive\Documents\Arduino\libraries\ArduinoBLE\src/BLEService.h:23,
                 from C:\Users\cruis\OneDrive\Documents\Arduino\libraries\ArduinoBLE\src/BLEDevice.h:25,
                 from C:\Users\cruis\Downloads\autopilot-main\autopilot-main\autopilot_basic\Bluetooth.h:8,
                 from C:\Users\cruis\Downloads\autopilot-main\autopilot-main\autopilot_basic\Bluetooth.cpp:2:
C:\Users\cruis\OneDrive\Documents\Arduino\libraries\ArduinoBLE\src/BLECharacteristic.h:91:8: note: candidate: 'void BLECharacteristic::addDescriptor(BLEDescriptor&)'
   void addDescriptor(BLEDescriptor& descriptor);
        ^~~~~~~~~~~~~
C:\Users\cruis\OneDrive\Documents\Arduino\libraries\ArduinoBLE\src/BLECharacteristic.h:91:8: note:   no known conversion for argument 1 from 'BLE2902*' to 'BLEDescriptor&'
C:\Users\cruis\Downloads\autopilot-main\autopilot-main\autopilot_basic\Bluetooth.cpp:179:36: error: 'class BLEService' has no member named 'createCharacteristic'; did you mean 'addCharacteristic'?
   FW_Characteristic = pOTAService->createCharacteristic(UUID_FW,BLECharacteristic::PROPERTY_NOTIFY | BLECharacteristic::PROPERTY_WRITE);
                                    ^~~~~~~~~~~~~~~~~~~~
                                    addCharacteristic
C:\Users\cruis\Downloads\autopilot-main\autopilot-main\autopilot_basic\Bluetooth.cpp:179:84: error: 'PROPERTY_NOTIFY' is not a member of 'BLECharacteristic'
   FW_Characteristic = pOTAService->createCharacteristic(UUID_FW,BLECharacteristic::PROPERTY_NOTIFY | BLECharacteristic::PROPERTY_WRITE);
                                                                                    ^~~~~~~~~~~~~~~
C:\Users\cruis\Downloads\autopilot-main\autopilot-main\autopilot_basic\Bluetooth.cpp:179:121: error: 'PROPERTY_WRITE' is not a member of 'BLECharacteristic'
   FW_Characteristic = pOTAService->createCharacteristic(UUID_FW,BLECharacteristic::PROPERTY_NOTIFY | BLECharacteristic::PROPERTY_WRITE);
                                                                                                                         ^~~~~~~~~~~~~~
C:\Users\cruis\Downloads\autopilot-main\autopilot-main\autopilot_basic\Bluetooth.cpp:180:49: error: no matching function for call to 'BLECharacteristic::addDescriptor(BLE2902*)'
   FW_Characteristic->addDescriptor(new BLE2902());
                                                 ^
In file included from C:\Users\cruis\OneDrive\Documents\Arduino\libraries\ArduinoBLE\src/BLEService.h:23,
                 from C:\Users\cruis\OneDrive\Documents\Arduino\libraries\ArduinoBLE\src/BLEDevice.h:25,
                 from C:\Users\cruis\Downloads\autopilot-main\autopilot-main\autopilot_basic\Bluetooth.h:8,
                 from C:\Users\cruis\Downloads\autopilot-main\autopilot-main\autopilot_basic\Bluetooth.cpp:2:
C:\Users\cruis\OneDrive\Documents\Arduino\libraries\ArduinoBLE\src/BLECharacteristic.h:91:8: note: candidate: 'void BLECharacteristic::addDescriptor(BLEDescriptor&)'
   void addDescriptor(BLEDescriptor& descriptor);
        ^~~~~~~~~~~~~
C:\Users\cruis\OneDrive\Documents\Arduino\libraries\ArduinoBLE\src/BLECharacteristic.h:91:8: note:   no known conversion for argument 1 from 'BLE2902*' to 'BLEDescriptor&'
C:\Users\cruis\Downloads\autopilot-main\autopilot-main\autopilot_basic\Bluetooth.cpp:181:22: error: 'class BLECharacteristic' has no member named 'setCallbacks'
   FW_Characteristic->setCallbacks(new otaCallback());
                      ^~~~~~~~~~~~
C:\Users\cruis\Downloads\autopilot-main\autopilot-main\autopilot_basic\Bluetooth.cpp:183:16: error: 'class BLEService' has no member named 'start'
   pOTAService->start();
                ^~~~~
Multiple libraries were found for "BLEDevice.h"
 Used: C:\Users\cruis\OneDrive\Documents\Arduino\libraries\ArduinoBLE
 Not used: C:\Users\cruis\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.11\libraries\BLE
 Not used: C:\Users\cruis\OneDrive\Documents\Arduino\libraries\ESP32_BLE_Arduino
Multiple libraries were found for "BLEServer.h"
 Used: C:\Users\cruis\OneDrive\Documents\Arduino\libraries\ESP32_BLE_Arduino
 Not used: C:\Users\cruis\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.11\libraries\BLE
exit status 1
Error compiling for board LOLIN D32.

**Comment by svdrummer** [comment]
As no one has had a compilation error, what library are you using for bluetooth. I am using the standard bluetooth library

**Comment by pieteroskam** [comment]
Ensure that your ESP32 board definitions and the ESP32 BLE library are up to date. Arduino IDE doesn't always update these automatically.

Go to the Board Manager and update the ESP32 package.
Check if there's an update for the ESP32 BLE Arduino library and update it.

Also make sure there arent any other bluetooth libraries with conflicting names.

**Comment by svdrummer** [comment]
Brand new clean install . Clearly the fault follows myself as no one else is having the issue.

**Comment by jeff-burright** [comment]
This part of your readout caught my eye. I wonder if it's grabbing the right library when it compiles. Maybe try deleting the other versions listed here?

Multiple libraries were found for "BLEDevice.h"
Used: C:\Users\cruis\OneDrive\Documents\Arduino\libraries\ArduinoBLE
Not used: C:\Users\cruis\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.11\libraries\BLE
Not used: C:\Users\cruis\OneDrive\Documents\Arduino\libraries\ESP32_BLE_Arduino
Multiple libraries were found for "BLEServer.h"
Used: C:\Users\cruis\OneDrive\Documents\Arduino\libraries\ESP32_BLE_Arduino
Not used: C:\Users\cruis\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.11\libraries\BLE
